from BaseClasses import Location

location_data = [
    ("VoR Courage Reactor", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 296, "overworld", [], 0, 0),
    ("VoR Utter Scrap", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 379, "overworld", [], 0, 1),
    ("VoR Pink Menace", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 360, "overworld", ["blue"], 0, 2),
    ("VoR Spiny Alien Treat", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 277, "overworld", ["blue"], 0, 3),
    ("VoR Temporal Mechanism", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 336, "overworld_enemy", ["blue"], 0, 4),
    ("VoR Unspeakable Wonder", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 315, "overworld", ["blue"], 0, 5),
    ("VoR Fossilized Ursidae", "files\\user\\Abe\\map\\tutorial\\initgen.txt", 258, "overworld", ["blue", "yellow"], 0, 6),
    ("EC Citrus Lump", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_1.txt", 38, "cave", [], 1, 26),
    ("EC Quenching Emblem", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_1.txt", 37, "cave", [], 1, 27),
    ("EC Spherical Atlas", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_1.txt", 87, "cave", [], 2, 26),
    ("SC Exhausted Superstick", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 55, "cave", ["blue", "white"], 1, 26),
    ("SC Nouveau Table", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 56, "cave", ["blue", "white"], 1, 27),
    ("SC Network Mainbrain", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 120, "cave", ["blue", "white"], 2, 26),
    ("SC Spirit Flogger", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 121, "cave", ["blue", "white"], 2, 27),
    ("SC Coiled Launcher", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 183, "cave", ["blue", "white"], 3, 26),
    ("SC Omega Flywheel", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 182, "cave", ["blue", "white"], 3, 27),
    ("SC Superstrong Stabilizer", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 162, "cave_enemy", ["blue", "white"], 3, 28),
    ("SC Adamantine Girdle", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 312, "cave", ["blue", "white"], 5, 26),
    ("SC Mystical Disc", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 311, "cave", ["blue", "white"], 5, 27),
    ("SC Repair Juggernaut", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 376, "cave", ["blue", "white"], 6, 26),
    ("SC Space Wave Receiver", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 375, "cave", ["blue", "white"], 6, 27),
    ("SC Vacuum Processor", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 374, "cave", ["blue", "white"], 6, 28),
    ("SC Furious Adhesive", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 445, "cave", ["blue", "white"], 7, 26),
    ("SC Indomitable CPU", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 414, "cave_enemy", ["blue", "white"], 7, 27),
    ("SC Thirst Activator", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 444, "cave", ["blue", "white"], 7, 28),
    ("SC Stellar Orb", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_2.txt", 539, "cave_enemy", ["blue", "white"], 9, 26),
    ("FC Essence of Rage", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 62, "cave", ["blue"], 1, 26),
    ("FC Essential Furnishing", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 61, "cave", ["blue"], 1, 27),
    ("FC Icon of Progress", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 122, "cave", ["blue"], 2, 26),
    ("FC Joy Receptacle", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 121, "cave", ["blue"], 2, 27),
    ("FC Danger Chime", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 159, "cave_enemy", ["blue"], 3, 26),
    ("FC Fleeting Art Form", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 182, "cave", ["blue"], 3, 27),
    ("FC Gemstar Husband", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 181, "cave", ["blue"], 3, 28),
    ("FC Innocence Lost", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 255, "cave", ["blue"], 4, 26),
    ("FC Omniscient Sphere", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 256, "cave", ["blue"], 4, 27),
    ("FC Brute Knuckles", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 309, "cave_enemy", ["blue"], 5, 26),
    ("FC Priceless Statue", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 402, "cave", ["blue"], 6, 26),
    ("FC Worthless Statue", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 401, "cave", ["blue"], 6, 27),
    ("FC Flame Tiller", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 462, "cave", ["blue"], 7, 26),
    ("FC Spouse Alert", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 463, "cave", ["blue"], 7, 27),
    ("FC Repugnant Appendage", "files\\user\\Mukki\\mapunits\\caveinfo\\tutorial_3.txt", 504, "cave_enemy", ["blue"], 8, 26),
    ("AW Sunseed Berry", "files\\user\\Abe\\map\\forest\\initgen.txt", 346, "overworld", [], 0, 7),
    ("AW Chance Totem", "files\\user\\Abe\\map\\forest\\initgen.txt", 365, "overworld", ["white"], 0, 8),
    ("AW Pilgrim Bulb", "files\\user\\Abe\\map\\forest\\initgen.txt", 441, "overworld", [], 0, 9),
    ("AW Geographic Projection", "files\\user\\Abe\\map\\forest\\initgen.txt", 327, "overworld", ["white"], 0, 10),
    ("AW Healing Cask", "files\\user\\Abe\\map\\forest\\initgen.txt", 422, "overworld", ["yellow"], 0, 11),
    ("AW Decorative Goo", "files\\user\\Abe\\map\\forest\\initgen.txt", 403, "overworld", ["yellow", "blue"], 0, 12),
    ("AW Air Brake", "files\\user\\Abe\\map\\forest\\initgen.txt", 384, "overworld", ["blue"], 0, 13),
    ("HoB Stone of Glory", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 50, "cave", [], 1, 26),
    ("HoB Cosmic Archive", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 144, "cave", [], 3, 26),
    ("HoB Strife Monolith", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 145, "cave", [], 3, 27),
    ("HoB Dream Architect", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 181, "cave_enemy", [], 4, 26),
    ("HoB Luck Wafer", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 193, "cave", [], 4, 27),
    ("HoB Prototype Detector", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_1.txt", 235, "cave_enemy", [], 5, 26),
    ("WFG Alien Billboard", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 43, "cave", ["purple"], 1, 26),
    ("WFG Drought Ender", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 84, "cave", ["purple"], 2, 26),
    ("WFG Petrified Heart", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 85, "cave", ["purple"], 2, 27),
    ("WFG Superstick Textile", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 136, "cave", ["purple"], 3, 26),
    ("WFG Survival Ointment", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 177, "cave", ["purple"], 4, 26),
    ("WFG Toxic Toadstool", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 178, "cave", ["purple"], 4, 27),
    ("WFG Five-man Napsack", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_2.txt", 213, "cave_enemy", ["purple"], 5, 26),
    ("BK Crystal Clover", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 31, "cave_enemy", ["white", "yellow"], 1, 26),
    ("BK Tear Stone", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 95, "cave", ["white", "yellow"], 2, 26),
    ("BK Olimarnite Shell", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 148, "cave", ["white", "yellow"], 3, 26),
    ("BK Crystal King", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 186, "cave_enemy", ["white", "yellow"], 4, 26),
    ("BK Unknown Merit", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 188, "cave_enemy", ["white", "yellow"], 4, 27),
    ("BK Anxious Sprout", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 267, "cave", ["white", "yellow"], 5, 26),
    ("BK Colossal Fossil", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 330, "cave", ["white", "yellow"], 6, 26),
    ("BK Eternal Emerald Eye", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 308, "cave_enemy", ["white", "yellow"], 6, 27),
    ("BK Forged Courage", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 389, "cave_enemy", ["white", "yellow"], 7, 26),
    ("BK Gyroid Bust", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_3.txt", 401, "cave", ["white", "yellow"], 7, 27),
    ("SH Crystallized Telekinesis", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 32, "cave_enemy", ["blue", "white"], 1, 26),
    ("SH Leviathan Feather", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 40, "cave", ["blue", "white"], 1, 27),
    ("SH Combustion Berry", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 96, "cave", ["blue", "white"], 2, 26),
    ("SH Taste Sensation", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 97, "cave", ["blue", "white"], 2, 27),
    ("SH Meat Satchel", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 139, "cave_enemy", ["blue", "white"], 3, 26),
    ("SH Crystallized Telepathy", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 220, "cave", ["blue", "white"], 4, 26),
    ("SH Cupid's Grenade", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 219, "cave", ["blue", "white"], 4, 27),
    ("SH Heavy-duty Magnetizer", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 201, "cave_enemy", ["blue", "white"], 4, 28),
    ("SH Crystallized Clairvoyance", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 261, "cave_enemy", ["blue", "white"], 5, 26),
    ("SH Emperor Whistle", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 259, "cave_enemy", ["blue", "white"], 5, 27),
    ("SH Salivatrix", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 333, "cave", ["blue", "white"], 6, 26),
    ("SH Science Project", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 332, "cave", ["blue", "white"], 6, 27),
    ("SH Stupendous Lens", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 316, "cave_enemy", ["blue", "white"], 6, 28),
    ("SH Triple Sugar Threat", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 314, "cave_enemy", ["blue", "white"], 6, 29),
    ("SH Justice Alloy", "files\\user\\Mukki\\mapunits\\caveinfo\\forest_4.txt", 383, "cave_enemy", ["blue", "white"], 7, 26),
    ("PP Gherkin Gate", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 382, "overworld", ["yellow"], 0, 14),
    ("PP Impediment Scourge", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 420, "overworld", ["yellow"], 0, 15),
    ("PP Aquatic Mine", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 338, "overworld_enemy", ["blue"], 0, 16),
    ("PP Fortified Delicacy", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 439, "overworld", ["blue"], 0, 17),
    ("PP Onion Replica", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 458, "overworld", ["blue"], 0, 18),
    ("PP Optical Illustration", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 401, "overworld", ["blue", "yellow"], 0, 19),
    ("PP Massage Girdle", "files\\user\\Abe\\map\\yakushima\\initgen.txt", 363, "overworld", ["blue"], 0, 20),
    ("CoS Love Nugget", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 48, "cave", [], 1, 26),
    ("CoS Creative Inspiration", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 90, "cave_enemy", [], 2, 26),
    ("CoS Lip Service", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 111, "cave", [], 2, 27),
    ("CoS Paradoxical Enigma", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 110, "cave", [], 2, 28),
    ("CoS Memorial Shell", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 169, "cave", [], 3, 26),
    ("CoS Patience Tester", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 170, "cave", [], 3, 27),
    ("CoS Flame of Tomorrow", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 234, "cave", [], 4, 26),
    ("CoS King of Sweets", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 217, "cave_enemy", [], 4, 27),
    ("CoS Time Capsule", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 233, "cave", [], 4, 28),
    ("CoS Regal Diamond", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 292, "cave", [], 5, 26),
    ("CoS The Key", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_1.txt", 278, "cave_enemy", [], 5, 27),
    ("GK Master's Instrument", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 42, "cave", ["yellow"], 1, 26),
    ("GK Massive Lid", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 98, "cave", ["yellow"], 2, 26),
    ("GK Imperative Cookie", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 99, "cave", ["yellow"], 2, 27),
    ("GK Director of Destiny", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 151, "cave", ["yellow"], 3, 26),
    ("GK Harmonic Synthesizer", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 152, "cave", ["yellow"], 3, 27),
    ("GK Invigorator", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 210, "cave", ["yellow"], 4, 26),
    ("GK Happiness Emblem", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 197, "cave_enemy", ["yellow"], 4, 27),
    ("GK White Goodness", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 209, "cave", ["yellow"], 4, 28),
    ("GK Boom Cone", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 260, "cave", ["yellow"], 5, 26),
    ("GK Sulking Antenna", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 261, "cave", ["yellow"], 5, 27),
    ("GK Dream Material", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 306, "cave_enemy", ["yellow"], 6, 26),
    ("GK Hideous Victual", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 323, "cave", ["yellow"], 6, 27),
    ("GK Meat of Champions", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 322, "cave", ["yellow"], 6, 28),
    ("GK Sweet Dreamer", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_2.txt", 324, "cave", ["yellow"], 6, 29),
    ("SR Merciless Extractor", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 48, "cave", ["yellow", "blue"], 1, 26),
    ("SR Durable Energy Cell", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 115, "cave", ["yellow", "blue"], 2, 26),
    ("SR Sud Generator", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 114, "cave", ["yellow", "blue"], 2, 27),
    ("SR Mirrored Stage", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 162, "cave_enemy", ["yellow", "blue"], 3, 26),
    ("SR Scrumptious Shell", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 177, "cave", ["yellow", "blue"], 3, 27),
    ("SR Vorpal Platter", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 176, "cave", ["yellow", "blue"], 3, 28),
    ("SR Arboreal Frippery", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 245, "cave", ["yellow", "blue"], 4, 26),
    ("SR Broken Food Master", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 299, "cave", ["yellow", "blue"], 5, 26),
    ("SR Endless Repository", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 300, "cave", ["yellow", "blue"], 5, 27),
    ("SR Pondering Emblem", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 301, "cave", ["yellow", "blue"], 5, 28),
    ("SR Abstract Masterpiece", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 373, "cave", ["yellow", "blue"], 6, 26),
    ("SR Behemoth Jaw", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 372, "cave", ["yellow", "blue"], 6, 27),
    ("SR Rubber Ugly", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 371, "cave", ["yellow", "blue"], 6, 28),
    ("SR Amplified Amplifier", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_3.txt", 423, "cave_enemy", ["yellow", "blue"], 7, 26),
    ("SMGC Bug Bait", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 34, "cave_enemy", ["blue"], 1, 26),
    ("SMGC Diet Doomer", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 53, "cave", ["blue"], 1, 27),
    ("SMGC Pastry Wheel", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 52, "cave", ["blue"], 1, 28),
    ("SMGC Chocolate Cushion", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 115, "cave", ["blue"], 2, 26),
    ("SMGC Comfort Cookie", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 99, "cave_enemy", ["blue"], 2, 27),
    ("SMGC Confection Hoop", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 116, "cave", ["blue"], 2, 28),
    ("SMGC Activity Arouser", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 156, "cave_enemy", ["blue"], 3, 26),
    ("SMGC Compelling Cookie", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 176, "cave", ["blue"], 3, 27),
    ("SMGC Succulent Mattress", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 177, "cave", ["blue"], 3, 28),
    ("SMGC Drone Supplies", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 249, "cave", ["blue"], 4, 26),
    ("SMGC Pale Passion", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 239, "cave_enemy", ["blue"], 4, 27),
    ("SMGC Proton AA", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 250, "cave", ["blue"], 4, 28),
    ("SMGC Professional Noisemaker", "files\\user\\Mukki\\mapunits\\caveinfo\\yakushima_4.txt", 291, "cave_enemy", ["blue", "purple"], 5, 26),
    ("WW Doomsday Apparatus", "files\\user\\Abe\\map\\last\\initgen.txt", 221, "overworld", [], 0, 21),
    ("WW Seed of Greed", "files\\user\\Abe\\map\\last\\initgen.txt", 288, "overworld_enemy", ["blue"], 0, 22),
    ("WW Anti-hiccup Fungus", "files\\user\\Abe\\map\\last\\initgen.txt", 313, "overworld", ["blue", "white"], 0, 23),
    ("WW Armored Nut", "files\\user\\Abe\\map\\last\\initgen.txt", 261, "overworld_enemy", ["blue"], 0, 24),
    ("WW Conifer Spire", "files\\user\\Abe\\map\\last\\initgen.txt", 240, "overworld", ["yellow"], 0, 25),
    ("CoC Enamel Buster", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 56, "cave", [], 1, 26),
    ("CoC Mirth Sphere", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 55, "cave", [], 1, 27),
    ("CoC Essence of Despair", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 98, "cave_enemy", [], 2, 26),
    ("CoC Frosty Bauble", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 96, "cave_enemy", [], 2, 27),
    ("CoC Gemstar Wife", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 94, "cave_enemy", [], 2, 28),
    ("CoC Child of the Earth", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 171, "cave", [], 3, 26),
    ("CoC Infernal Vegetable", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 170, "cave", [], 3, 27),
    ("CoC Milk Tub", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 231, "cave", [], 4, 26),
    ("CoC Mysterious Remains", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 211, "cave_enemy", [], 4, 27),
    ("CoC Growshroom", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 347, "cave", [], 6, 26),
    ("CoC Princess Pearl", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 331, "cave_enemy", [], 6, 27),
    ("CoC Fuel Reservoir", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 404, "cave", [], 7, 26),
    ("CoC Impenetrable Cookie", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 382, "cave_enemy", [], 7, 27),
    ("CoC Fruit Guard", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 468, "cave", [], 8, 26),
    ("CoC Maternal Sculpture", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 522, "cave", [], 9, 26),
    ("CoC Wiggle Noggin", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 523, "cave", [], 9, 27),
    ("CoC Silencer", "files\\user\\Mukki\\mapunits\\caveinfo\\last_1.txt", 558, "cave_enemy", [], 10, 26),
    ("HoH Corpulent Nut", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 55, "cave", ["yellow"], 1, 26),
    ("HoH Essence of True Love", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 116, "cave", ["yellow"], 2, 26),
    ("HoH Love Sphere", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 177, "cave", ["yellow"], 3, 26),
    ("HoH Lustrous Element", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 217, "cave_enemy", ["yellow"], 4, 26),
    ("HoH Nutrient Silo", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 337, "cave", ["yellow", "blue"], 6, 26),
    ("HoH Joyless Jewel", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 378, "cave_enemy", ["yellow"], 7, 26),
    ("HoH Dimensional Slicer", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 476, "cave_enemy", ["yellow"], 9, 26),
    ("HoH Treasured Gyro Block", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 534, "cave_enemy", ["yellow"], 10, 26),
    ("HoH Favorite Gyro Block", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 584, "cave_enemy", ["yellow"], 11, 26),
    ("HoH Lost Gyro Block", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 628, "cave_enemy", ["yellow"], 12, 26),
    ("HoH Memorable Gyro Block", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 681, "cave_enemy", ["yellow", "blue"], 13, 26),
    ("HoH Fond Gyro Block", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 721, "cave_enemy", ["yellow", "blue"], 14, 26),
    ("HoH Remembered Old Buddy", "files\\user\\Mukki\\mapunits\\caveinfo\\last_2.txt", 785, "cave_enemy", ["yellow"], 15, 26),
    ("DD Disguised Delicacy", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 48, "cave", ["blue", "white"], 1, 26),
    ("DD Implement of Toil", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 94, "cave", ["blue", "white"], 2, 26),
    ("DD Manual Honer", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 84, "cave_enemy", ["blue", "white"], 2, 27),
    ("DD Glee Spinner", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 130, "cave_enemy", ["blue", "white"], 3, 26),
    ("DD Mirrored Element", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 203, "cave", ["blue", "white"], 4, 26),
    ("DD Insect Condo", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 239, "cave_enemy", ["blue", "white"], 5, 26),
    ("DD Future Orb", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 294, "cave_enemy", ["blue", "white"], 6, 26),
    ("DD Essence of Desire", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 346, "cave_enemy", ["blue", "white"], 7, 26),
    ("DD Extreme Perspirator", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 430, "cave", ["blue", "white"], 8, 26),
    ("DD Possessed Squash", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 429, "cave", ["blue", "white"], 8, 27),
    ("DD Talisman of Life", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 517, "cave_enemy", ["blue", "white"], 10, 26),
    ("DD Boss Stone", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 598, "cave", ["blue", "white"], 11, 26),
    ("DD Yellow Taste Tyrant", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 599, "cave", ["blue", "white"], 11, 27),
    ("DD Stringent Container", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 635, "cave_enemy", ["blue", "white"], 12, 26),
    ("DD Universal Com", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 655, "cave", ["blue", "white"], 12, 27),
    ("DD Hypnotic Platter", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", 693, "cave_enemy", ["blue", "white"], 13, 26),
    ("DD Comedy Bomb", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", -1, "cave", ["blue", "white"], 14, 26),
    ("DD Flare Cannon", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", -1, "cave", ["blue", "white"], 14, 27),
    ("DD Monster Pump", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", -1, "cave", ["blue", "white"], 14, 28),
    ("DD Shock Therapist", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", -1, "cave", ["blue", "white"], 14, 29),
    ("DD King of Bugs", "files\\user\\Mukki\\mapunits\\caveinfo\\last_3.txt", -1, "cave", ["blue", "white"], 14, 30)
]

caves = {
    0x745F3031: "EC",
    0x745F3032: "SC",
    0x745F3033: "FC",
    0x665F3031: "HoB",
    0x665F3032: "WFG",
    0x665F3033: "BK",
    0x665F3034: "SH",
    0x795F3031: "CoS",
    0x795F3032: "GK",
    0x795F3033: "SR",
    0x795F3034: "SMGC",
    0x6C5F3031: "CoC",
    0x6C5F3032: "HoH",
    0x6C5F3033: "DD"
}

vor_prefixes = ["VoR", "EC", "FC", "SC"]
aw_prefixes = ["AW", "HoB", "WFG", "BK", "SH"]
pp_prefixes = ["PP", "CoS", "GK", "SR", "SMGC"]
ww_prefixes = ["WW", "CoC", "HoH", "DD"]
pikmin2_locations = [loc[0] for loc in location_data]
impossible_buried_treasure_locations = ["VoR Courage Reactor", "VoR Temporal Mechanism", "VoR Fossilized Ursidae", "FC Priceless Statue", "FC Worthless Statue", "AW Healing Cask", "AW Decorative Goo", "AW Air Brake", "PP Gherkin Gate", "PP Impediment Scourge", "PP Massage Girdle", "SR Broken Food Master", "SR Endless Repository", "SMGC Bug Bait", "SMGC Diet Doomer", "SMGC Pastry Wheel", "SMGC Chocolate Cushion", "SMGC Comfort Cookie", "SMGC Confection Hoop", "CoC Milk Tub", "CoC Mysterious Remains", "CoC Growshroom", "CoC Princess Pearl", "CoC Maternal Sculpture", "CoC Wiggle Noggin", "HoH Nutrient Silo", "HoH Memorable Gyro Block", "HoH Fond Gyro Block", "DD Manual Honer", "DD Talisman of Life", "DD Boss Stone", "DD Yellow Taste Tyrant"]

class Pikmin2Location(Location):
    game: str = "Pikmin 2"
    def __init__(self, player, name, address, parent):
        super().__init__(player, name, address, parent)
