import os
import tempfile
import logging
import importlib.util
import pkgutil
import importlib.resources as resources

FALLBACK_STYLE_KV = b"# autogenerated fallback style.kv\n\n"

def ensure_kivy_data_available():
    try:
        spec = importlib.util.find_spec("kivy")
        if not spec:
            return

        origin = getattr(spec, "origin", "") or ""
        package_dir = os.path.dirname(origin)
        needs_extract = origin.endswith(".zip") or not os.path.isdir(package_dir)
        if not needs_extract:
            return

        tmp = tempfile.mkdtemp(prefix="kivy_data_")
        target_data_dir = os.path.join(tmp, "kivy", "data")
        os.makedirs(target_data_dir, exist_ok=True)

        fname = "style.kv"
        out_path = os.path.join(target_data_dir, fname)

        data = None
        # Try importlib.resources (modern API)
        try:
            if hasattr(resources, "files"):
                try:
                    data = resources.files("kivy").joinpath("data").joinpath(fname).read_bytes()
                except Exception:
                    data = None
        except Exception:
            data = None

        # Fallback to pkgutil.get_data
        if data is None:
            try:
                data = pkgutil.get_data("kivy", f"data/{fname}")
            except Exception:
                data = None

        try:
            if data:
                with open(out_path, "wb") as fh:
                    fh.write(data)
            else:
                logging.warning("kivy resource %s not found in package, writing fallback", fname)
                with open(out_path, "wb") as fh:
                    fh.write(FALLBACK_STYLE_KV)
        except Exception:
            logging.exception("Failed writing local kivy data file %s", out_path)

        # Force override so Kivy reads the extracted filesystem files
        os.environ["KIVY_DATA_DIR"] = tmp
    except Exception:
        logging.exception("ensure_kivy_data_available failed (best-effort)")

# Run on import so importing this module preps the environment early
try:
    ensure_kivy_data_available()
except Exception:
    logging.exception("Failed running ensure_kivy_data_available at module import")